[gcp_service_account]
type = "service_account"
project_id = "antimicrobial-data-sheet"
private_key_id = "38f38dc79ee6f3f36da62b2afc9b808b2e3be1f6"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDPUc38i9RdMPyd
... (rest of your key) ...
-----END PRIVATE KEY-----"""
client_email = "dseek-data-antimicrobial@antimicrobial-data-sheet.iam.gserviceaccount.com"
client_id = "117493900348644313899"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/dseek-data-antimicrobial%40antimicrobial-data-sheet.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

spreadsheet_id = "1h4g3LSI4hZgkSF9NVcQWV_qLMATbAjt5QxSzCvldElg"
